"""Session-start fixture hooks and context-delivery assertions."""

import json
import re

from .conversation import Conversation
from .harness_support import write_json
from .plugin_fixture import PluginFixture
from .skill_assertions import audit_messages

TOKEN = re.compile(r"SESSION-[0-9a-f]{32}")


def make_session_fixture(run, case, *, emit):
    plugin = PluginFixture.create(run.root, run.harness)
    capture = run.root / f"{case}.hook.json"
    script = plugin.path / "hooks/session-start.py"
    script.parent.mkdir(parents=True, exist_ok=True)
    # The token is generated by the hook, never placed in the user prompt or
    # plugin metadata. Captures live outside the workspace and reads fail audit.
    script.write_text(
        "import json, secrets, sys\nfrom pathlib import Path\n"
        "payload = json.load(sys.stdin)\n"
        "token = 'SESSION-' + secrets.token_hex(16)\n"
        f"emit = {emit!r}\n"
        f"Path({str(capture)!r}).write_text(json.dumps({{'payload': payload, 'token': token, 'emitted': emit}}))\n"
        "context = 'Session-start token: ' + token if emit else ''\n"
        + ("print(json.dumps({'additional_context': context}))\n" if run.harness == "cursor" else
           "print(json.dumps({'hookSpecificOutput': {'hookEventName': 'SessionStart', 'additionalContext': context}}))\n")
    )
    variable = "CURSOR_PLUGIN_ROOT" if run.harness == "cursor" else "CLAUDE_PLUGIN_ROOT"
    hook = {"type": "command", "command": f'python3 "${{{variable}}}/hooks/session-start.py"'}
    config = ({"version": 1, "hooks": {"sessionStart": [hook]}} if run.harness == "cursor" else
              {"hooks": {"SessionStart": [{"hooks": [hook]}]}})
    write_json(plugin.path / "hooks/hooks.json", config)
    return plugin, capture


def session_evidence(conversation: Conversation, output, capture, *, emitted,
                     request_context: Conversation | None = None):
    audit_messages(conversation)
    if not output.strip():
        raise RuntimeError("empty model response")
    token = capture.get("token")
    if not isinstance(token, str) or not TOKEN.fullmatch(token):
        raise RuntimeError("missing or malformed hook token")
    if capture.get("emitted") is not emitted:
        raise RuntimeError("hook emission mode does not match the control")
    context = request_context if request_context is not None else conversation
    if context.calls or context.results:
        raise RuntimeError("tool activity in request context")
    incoming = "\n".join(text for _, text in context.incoming)
    if emitted:
        if token not in output:
            raise RuntimeError("hook ran but token was not recovered")
        if token not in incoming:
            raise RuntimeError("token absent from incoming context; assistant echo alone is insufficient")
    elif TOKEN.search(incoming) or TOKEN.search(output):
        raise RuntimeError("session token leaked from the silent hook control")
    return {"hook_executed": True, "context_emitted": emitted,
            "context_received": emitted, "tool_use": False,
            "evidence": "API request + transcript audit" if request_context is not None else "conversation record"}
