name: ci

on:
  push:
    branches: [src]
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v5

      - uses: DeterminateSystems/determinate-nix-action@v3.22.3
        with:
          extra-conf: |
            extra-substituters = https://devenv.cachix.org
            extra-trusted-public-keys = devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=

      - name: Install devenv
        run: nix profile add github:cachix/devenv/v2.2.1

      - name: Build the shell and run the test tasks
        run: devenv test
